name: impfe # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: GUI client for the online multiplayer game Imperium
description: |
  This is a GUI client for the online multiplayer strategy game Imperium

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: impfeicon.png
title: ImpFE

apps:
  impfe:
    command: bin/impfe
parts:
  impfe:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [libforms-bin, libforms-dev, libao-common, libao-dev, libmpg123-0]
    stage-packages: [libforms-bin, libforms-dev, libao-common, libao-dev, libmpg123-0]
    organize:
      impfe: bin/

architectures:
  build-on: amd64

